---
- hosts: all
  become: true
  tasks:
        - name: Copy service file
          template:
            src: tailscale-cert.service.j2
            dest: /etc/systemd/system/tailscale-cert.service

        - name: Copy timer file
          template:
            src: tailscale-cert.timer.j2
            dest: /etc/systemd/system/tailscale-cert.timer
